### ISSUE TITLE
Report file not being generated

### ISSUE THREAD

**Issue by ziggurat** [codecov/codecov-ruby#4]
I am getting this after running rspec:

    {"url": "http://codecov.io/bitbucket/prodetotal/prodetotal?    ref=182376c518e87447a8c73a91a8bae1526cc59c4c", "meta": {"status": 200, "request": "400cf6a4-1c95-    437e-a1ca-ef7d3dafc939"}, "uploaded": true, "queued": true, "message": "Coverage reports upload     successfully"}

But still no report on the site. If I run the bash command manually I got:

    Codecov
    (version) 7749084
    (url) https://codecov.io
    ==> No CI detected, using git for branch and commit sha.
    ==> find . -type f -name '*.gcno'  -exec gcov  {} +
    ==> Searching for coverage reports
    **> Python coverage not found
    **> No coverage report found.

**Comment by stevepeak** [comment]
Hey @ziggurat currently the Bash uploader is not compatible with Ruby. I will work to support it in the near future but for now you'll need to follow the directions on the readme to integrate with Codecov: https://github.com/codecov/codecov-ruby/blob/master/README.md

Thanks!

**Comment by ziggurat** [comment]
Hi @stevepeak . I have a bitbucket project and a CI environment in CodeShip. Evetyhing is configured as indicated in the readme but I still get "No reports uploaded" and the instructions are to use the bash script. Any hints?

**Comment by stevepeak** [comment]
@ziggurat can you try to push us another build. I saw an issue with building your report that I have fixed. Thank you!

**Comment by ziggurat** [comment]
@stevepeak Perfect!! It's working now. Thanks!!

**Comment by akun1** [comment]
Any work done to support Ruby now? Still getting similar error 5 years later 😅

![Screen Shot 2020-10-28 at 12 13 21 PM](https://user-images.githubusercontent.com/23622603/97471694-faa4a080-1916-11eb-83e7-97b6b41945b3.png)
